# docker-compose up --build
version: "3.9"
services:
  server:
    build: 
      context: ./
      dockerfile: ./docker/server/Dockerfile
      args:
        - SERVICE=grpcserver
    ports:
      - "8081:8080"
  client:
    build: 
      context: ./
      dockerfile: ./docker/client/Dockerfile
      args:
        - SERVICE=client
    ports:
      - "8082:8080" 
    depends_on:
      - server